### ISSUE TITLE
Task distribution. 

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework5G3#10]
Hello dear members of the group. We have to distribute the tasks for the group, right? @LinxuanHu @s4il3sh

**Comment by s4il3sh** [comment]
Yes. We need to do it. I will try unit testing.

**Comment by s4il3sh** [comment]
Or I can also go for Algorithm.

**Comment by s4il3sh** [comment]
Let's divide our roles on these basis:
Algorithm -? 
Documentation - ? 
Unittest -? 
Maintainer - @uarif

**Comment by reshnashrestha** [comment]
Who is going to do the algorithm part? Can you share some insights on that?

**Comment by s4il3sh** [comment]
I just realized that we need to divide our tasks on the basis of task1, task2, and task3 which is the requirement of our homework.  Well, I will choose task1. Is that ok with you guys?

**Comment by uarif** [comment]
Okay, I will do scond task then

**Comment by uarif** [comment]
I will do second task then @s4il3sh @LinxuanHu
