### ISSUE TITLE
Task 1 Confusion

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework5G3#14]
Hi group 3,
Who is doing task 1 of homework 5? Please give a brief overview about task 1. I am confused what exactly we will be doing on it?

**Comment by reshnashrestha** [comment]
@pratibha77118 I followed the hands-on by professor for task 1

**Comment by uarif** [comment]
I think that should be @s4il3sh  @pratibha77118

**Comment by tirthbha** [comment]
@pratibha77118 For task 1, we need to do
Use Fast Fourier Transform (FFT) to analyze CO2 concentration data:
    - Calculated actual frequencies from the FFT output in cycles per month, if I were not wrong for the unit.
    - Identified peak frequencies in the data by analyzing the FFT results.
