### ISSUE TITLE
Work assignment, 

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework5G3#27]
Hello guys, Since, there is a communication gape, and the deadline is coming. As per @s4il3sh , Lets he do the Task 01. I will do task 2. I have already started. And @LinxuanHu  can do task 3. 
But we both have to do our part soon, so that he has time for his task @s4il3sh . 
Thank you.

**Comment by LinxuanHu** [comment]
ok

**Comment by Mosaddeq107** [comment]
> Hello guys, Since, there is a communication gape, and the deadline is coming. As per @s4il3sh , Lets he do the Task 01. I will do task 2. I have already started. And @LinxuanHu can do task 3. But we both have to do our part soon, so that he has time for his task @s4il3sh . Thank you.

Nice distribution. Keep doing your jobs.

**Comment by Pranjal-Srivastava-2023** [comment]
> > Hello guys, Since, there is a communication gape, and the deadline is coming. As per @s4il3sh , Lets he do the Task 01. I will do task 2. I have already started. And @LinxuanHu can do task 3. But we both have to do our part soon, so that he has time for his task @s4il3sh . Thank you.
> 
> Nice distribution. Keep doing your jobs.

@Mosaddeq107 Thank you for you comment.
