### ISSUE TITLE
station selection (Ascension Island, United Kingdom (ASC))

### ISSUE THREAD

**Issue by LinxuanHu** [ubsuny/23-Homework5G3#3]
we can use the data of the station Ascension Island, United Kingdom (ASC), what do you think

**Comment by reshnashrestha** [comment]
Are you going to select this?

**Comment by uarif** [comment]
Any data is fine @LinxuanHu

**Comment by s4il3sh** [comment]
I am OK with any data.

**Comment by LinxuanHu** [comment]
let's choose Ascension Island, United Kingdom (ASC)
