### ISSUE TITLE
maintainer

### ISSUE THREAD

**Issue by LinxuanHu** [ubsuny/23-Homework5G3#4]
who want to be the maintainer

**Comment by uarif** [comment]
I am fine with ever. @LinxuanHu

**Comment by uarif** [comment]
I can be the maintainer, if it's fine with you people.

**Comment by s4il3sh** [comment]
I am OK with you being a maintainer.

**Comment by reshnashrestha** [comment]
Who is doing the algorithm ?

**Comment by LinxuanHu** [comment]
> I can be the maintainer, if it's fine with you people.

sure, you can let prof tim know that

**Comment by uarif** [comment]
> Who is doing the algorithm ?

@s4il3sh
