### ISSUE TITLE
peak frequency calculation

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework5G3#45]
Have you figured out how to calculate peak frequency?

**Comment by pratibha77118** [comment]
I think they have done it @reshnashrestha .

**Comment by s4il3sh** [comment]
> Have you figured out how to calculate peak frequency?

We tried our best to calculate the peak frequency. Take a look any suggestions are welcome.

**Comment by reshnashrestha** [comment]
Oh okay , I will.
