### ISSUE TITLE
Station Chosen By G5

### ISSUE THREAD

**Issue by AhmedCode99** [ubsuny/23-Homework5G3#51]
Cape Kumukahi, Hawaii, United States (KUM)

**Comment by uarif** [comment]
Okay, Good luck

**Comment by LinxuanHu** [comment]
we choose Ascension Island, United Kingdom (ASC)

**Comment by s4il3sh** [comment]
@AhmedCode99 Nice. Is it working good?

**Comment by Pranjal-Srivastava-2023** [comment]
> we choose Ascension Island, United Kingdom (ASC)

Is it working?

**Comment by LinxuanHu** [comment]
> > we choose Ascension Island, United Kingdom (ASC)
> 
> Is it working?

it works
