### ISSUE TITLE
milestone usage

### ISSUE THREAD

**Issue by s4il3sh** [ubsuny/23-Homework5G3#59]
We have set milestone but we are not using it.

**Comment by reshnashrestha** [comment]
Who is the maintainer?

**Comment by Pranjal-Srivastava-2023** [comment]
> We have set milestone but we are not using it.

@s4il3sh if you have worked on the issues in the milestone then you can close them.

**Comment by uarif** [comment]
I am the maintainer @reshnashrestha

**Comment by uarif** [comment]
Just closed two @s4il3sh

**Comment by LinxuanHu** [comment]
i tried to use it in my issue
